### ISSUE TITLE
Ability to provide path to README.md file via CLI parameter

### ISSUE THREAD

**Issue by hollote** [bahmutov/dependency-version-badge#23]
Please add an ability to provide path to README.md via CLI parameter 

In the project I'm working on, I have BE and FE within the same repo. need to pass badge within the main README.md.

https://github.com/bahmutov/dependency-version-badge/blob/7c2af257d2627e4987762d515f9028b9ee3ac482/src/utils.js#L246

**Comment by bahmutov** [comment]
I’m open to a pull request to add this feature

**Comment by hollote** [comment]
https://github.com/bahmutov/dependency-version-badge/pull/24
